import { noteState } from "./types/notesReducerTypes";

export const notesDB: noteState[] = [
  {
    id: 1650064978318,
    name: "Note #1",
    category: "Idea",
    creationDate: "Apr 16, 2022",
    text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. 22.12.2003 Sed vel urna id ante porta dignissim quis non metus. Vestibulum eget ultrices nisl. Praesent tincidunt sem ut facilisis varius. Donec gravida sem purus, ac elementum erat faucibus in. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Praesent eu tristique nisi. Aliquam in lacus facilisis, tincidunt diam id, posuere lectus. Praesent pellentesque et tellus tincidunt mollis. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Pellentesque rhoncus ultrices magna ac dignissim. Quisque mattis est eget 13/02/2021 egestas tempor. Duis tristique sollicitudin lacinia. Nam imperdiet magna non orci vulputate elementum. Etiam vel neque at lorem dictum dictum. Nulla eget tellus nibh. In finibus ut arcu eu convallis.",
    isArchived: false,
    internalDates: ["22.12.2003", "13/02/2021"],
  },
  {
    id: 1650064992048,
    name: "Note #2",
    category: "Task",
    creationDate: "Apr 16, 2022",
    text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed vel urna id ante porta dignissim quis non metus. Vestibulum eget ultrices nisl. Praesent tincidunt sem ut facilisis varius. Donec gravida sem purus, ac elementum erat faucibus in. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Praesent eu tristique nisi. Aliquam in lacus facilisis, tincidunt diam id, posuere lectus. Praesent pellentesque et tellus tincidunt mollis. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Pellentesque rhoncus ultrices magna ac dignissim. Quisque mattis est eget egestas tempor. Duis tristique sollicitudin lacinia. Nam imperdiet magna non orci vulputate elementum. Etiam vel neque at lorem dictum dictum. Nulla eget tellus nibh. In finibus ut arcu eu convallis.",
    isArchived: true,
    internalDates: [],
  },
  {
    id: 1650065002143,
    name: "Note #3",
    category: "Random Thought",
    creationDate: "Apr 16, 2022",
    text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed vel urna id ante porta dignissim quis non metus. Vestibulum eget ultrices nisl. Praesent tincidunt sem ut facilisis varius. Donec gravida sem purus, ac elementum erat faucibus in. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Praesent eu tristique nisi. Aliquam in lacus facilisis, tincidunt diam id, posuere lectus. Praesent pellentesque et tellus tincidunt mollis. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Pellentesque rhoncus ultrices magna ac dignissim. Quisque mattis est eget egestas tempor. Duis tristique sollicitudin lacinia. Nam imperdiet magna non orci vulputate elementum. Etiam vel neque at lorem dictum dictum. Nulla eget tellus nibh. In finibus ut arcu eu convallis.",
    isArchived: true,
    internalDates: [],
  },
  {
    id: 1650065011609,
    name: "Note #22",
    category: "Task",
    creationDate: "Apr 16, 2022",
    text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed vel urna id ante porta dignissim quis non metus. Vestibulum eget ultrices nisl. Praesent tincidunt sem ut facilisis varius. Donec gravida sem purus, ac elementum erat faucibus in. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Praesent eu tristique nisi. Aliquam in lacus facilisis, tincidunt diam id, posuere lectus. Praesent pellentesque et tellus tincidunt mollis. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Pellentesque rhoncus ultrices magna ac dignissim. Quisque mattis est eget egestas tempor. Duis tristique sollicitudin lacinia. Nam imperdiet magna non orci vulputate elementum. Etiam vel neque at lorem dictum dictum. Nulla eget tellus nibh. In finibus ut arcu eu convallis.",
    isArchived: false,
    internalDates: [],
  },
  {
    id: 1650065034194,
    name: "Note #14",
    category: "Idea",
    creationDate: "Apr 16, 2022",
    text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed vel urna id ante porta dignissim quis non metus. Vestibulum eget ultrices nisl. Praesent tincidunt sem ut facilisis varius. Donec gravida sem purus, ac elementum erat faucibus in. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Praesent eu tristique nisi. Aliquam in lacus facilisis, tincidunt diam id, posuere lectus. Praesent pellentesque et tellus tincidunt mollis. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Pellentesque rhoncus ultrices magna ac dignissim. Quisque mattis est  eget egestas tempor. Duis tristique sollicitudin lacinia. Nam imperdiet magna non orci 12/24/1996 vulputate elementum. Etiam vel neque at lorem dictum dictum. Nulla eget tellus nibh. In finibus ut arcu eu convallis.",
    isArchived: true,
    internalDates: ["12/24/1996"],
  },
  {
    id: 1650065049913,
    name: "Note #123",
    category: "Random Thought",
    creationDate: "Apr 16, 2022",
    text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed vel urna id ante porta dignissim quis non metus. Vestibulum eget ultrices nisl. Praesent tincidunt sem ut facilisis varius. Donec gravida sem purus, ac elementum erat faucibus in. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Praesent eu tristique nisi. Aliquam in lacus facilisis, tincidunt diam id, posuere lectus. Praesent pellentesque et tellus tincidunt mollis. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Pellentesque rhoncus ultrices magna ac dignissim. Quisque mattis est eget egestas tempor. Duis tristique sollicitudin lacinia. Nam imperdiet magna non orci vulputate elementum. Etiam vel neque at lorem dictum dictum. Nulla eget tellus nibh. In finibus ut arcu eu convallis.",
    isArchived: false,
    internalDates: [],
  },
  {
    id: 1650065105404,
    name: "Note #133",
    category: "Task",
    creationDate: "Apr 16, 2022",
    text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed vel 20.02.2220 urna id ante porta dignissim quis non metus. Vestibulum eget ultrices nisl. Praesent tincidunt sem ut facilisis varius. Donec gravida sem purus, ac elementum erat faucibus in. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Praesent eu tristique nisi. Aliquam in lacus facilisis, tincidunt diam id, posuere lectus. Praesent pellentesque et tellus tincidunt mollis. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Pellentesque rhoncus ultrices magna ac dignissim. Quisque mattis est eget egestas tempor. Duis tristique sollicitudin lacinia. Nam imperdiet magna non orci vulputate elementum. Etiam vel neque at lorem dictum dictum. Nulla eget tellus nibh. In finibus ut arcu eu convallis.",
    isArchived: false,
    internalDates: ["20.02.2220"],
  },
];
